version: "3"

tasks:
  build:
    desc: "Build"
    cmds:
      - go build ./cmd/deployment/main.go
  run:
    desc: "Build & Run"
    deps:
      - build
    cmds:
      - ./main -config=./config/local.yaml
  db_raise:
    desc: "Raise database in container"
    cmds:
      - docker compose up -d
  init:
    desc: "Run in dev"
    deps:
      - db_raise
      - run
