env: "local" # dev, prod
grpc: 
  port: 50059
  timeout: 10h
kafka:
  servers:
    - "localhost:29092"
  topics:
    deployment_request:
      name: "NewZip"
      enabled: true
postgres_db:
  host: localhost
  port: 54324
  user: postgres
  password: postgres
  db_name: deployment-service
